# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[file:cmip6_datasets.nl]
source=(namelist:cmip6_datasets(:))

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:cmip6_datasets(1)]
experiment_id="historical"
grid="gn"
institute="MOHC"
label_for_plots="CMIP6 dataset 001"
model_id="UKESM1-0-LL"
variant_label="r5i1p1f3"

[namelist:model_runs(1)]
calendar="gregorian"
experiment_id="amip"
label_for_plots="HadGEM3-GC5E-LL N96ORCA1"
model_id="HadGEM3-GC5E-LL"
suite_id="u-cw673"
variant_label="r1i1p1f1"

[namelist:model_runs(2)]
calendar="360_day"
experiment_id="historical"
label_for_plots="HadGEM3-GC3.1 N96ORCA1"
model_id="HadGEM3-GC31-LL"
suite_id="u-bv526"
variant_label="r5i1p1f3"

[template variables]
AUTOASSESS=false
!!AUTOASSESS_TITLE=""
CDDS_VERSION=""
DRS_ANA4MIPS="default"
DRS_CMIP3="default"
DRS_CMIP5="default"
DRS_CMIP6="default"
DRS_CORDEX="default"
DRS_NATIVE6="default"
DRS_OBS="default"
DRS_OBS4MIPS="default"
DRS_OBS6="default"
ESMVALTOOL_MODULE_NAME=""
LABEL_FOR_PLOTS="HadGEM3-GC5E-LL N96ORCA1"
MAX_PARALLEL_TASKS=4
MIP_TABLE_DIR=""
MIP_TABLE_VERSION=""
NUMBER_OF_YEARS=2
!!RAW_DATA_DIR=""
RAW_DATA_DIR_MODE="off"
REF_LABEL_FOR_PLOTS="HadGEM3-GC3.1 N96ORCA1"
REF_SUITE_ID="u-bv526"
ROOTPATH_ANA4MIPS=""
ROOTPATH_CMIP3=""
ROOTPATH_CMIP5=""
ROOTPATH_CMIP6=""
ROOTPATH_CORDEX=""
ROOTPATH_NATIVE6=""
ROOTPATH_OBS=""
ROOTPATH_OBS4MIPS=""
ROOTPATH_OBS6=""
ROOTPATH_RAWOBS=""
SITE=""
START_YEAR=1993
SUITE_ID="u-cw673"
TEST=false
UNITTEST=false
